services:
  db:
    image: postgres:17-alpine
    container_name: todo-db
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=todos
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d todos"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-todo
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=local
      - PORT=8081
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=todos
      - DB_USER=demo
      - DB_PASSWORD=demo
      - DB_IAM_AUTH=false
      - DB_SSL=false
    ports:
      - "8081:8081"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - NODE_ENV=development
        - VITE_API_URL=http://localhost:8081
    container_name: frontend-todo
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started

    ports:
      - '8080:8080'

  migrate:
    build:
      context: .
      dockerfile: migration/Dockerfile
    container_name: migrate-todo
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=todos
      - DB_USER=demo
      - DB_PASSWORD=demo
      - DB_IAM_AUTH=false
      - DB_SSL=false


volumes:
  pg_data:
