apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config-map
  namespace: app
data:
  PORT: "8081"
  NODE_ENV: "production"
  OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger.tracing.svc.cluster.local:4318/v1/traces"
  OTEL_LOG_LEVEL: "debug"
  DB_IAM_AUTH: "true"
  DB_SSL: "true"
  DB_SSL_CA_FILE: "/app/certs/rds-global-bundle.pem"


