apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 078238935484.dkr.ecr.ap-south-1.amazonaws.com/eks-todo-backend:9f0298f681674b30521c63c42a9e46a279dead0b
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-config-map
