# ============================================================
#  Dockerfile.agent
#  The Jenkins build agent that runs the pipelines. Includes:
#  Docker CLI, SonarScanner and AWS CLI v2.
# ============================================================
FROM jenkins/inbound-agent:latest

USER root

# Install the Docker CLI
RUN apt-get update \
    && apt-get install -y docker.io

RUN apt-get install -y unzip curl \
    && curl -sSLo /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-8.1.0.6389-linux-x64.zip \
    && unzip -q /tmp/sonar-scanner.zip -d /opt \
    && mv /opt/sonar-scanner-8.1.0.6389-linux-x64 /opt/sonar-scanner \
    && rm /tmp/sonar-scanner.zip \
    && ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

# Install AWS CLI v2 (used to get the temporary ECR login password)
RUN curl -sSLo /tmp/awscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" \
    && unzip -q /tmp/awscliv2.zip -d /tmp \
    && /tmp/aws/install \
    && rm -rf /tmp/awscliv2.zip /tmp/aws \
    && aws --version

# Let the agent's 'jenkins' user use the Docker socket (match host GID)
ARG DOCKER_GID=999
RUN groupmod -g ${DOCKER_GID} docker || groupadd -g ${DOCKER_GID} docker
RUN usermod -aG docker jenkins

USER jenkins
