apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: monitoring
  name: backend-service-monitor
  namespace: monitoring
spec:
  endpoints:
    - interval: 2s
      port: backend
      path: /metrics
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - app
