apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: app
spec:
  selector:
    app: frontend # select the users pod and expose
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  template:
    spec:
      containers:
        - image: 078238935484.dkr.ecr.ap-south-1.amazonaws.com/eks-todo-frontend:0b831fb0a7ec2339d61c269142a14624cf48025c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend # label by which pod can be selected
    spec:
      containers:
        - name: frontend-container
          ports:
            - containerPort: 8080
          image: 078238935484.dkr.ecr.ap-south-1.amazonaws.com/eks-todo-frontend:0b831fb0a7ec2339d61c269142a14624cf48025c
          imagePullPolicy: Always
