apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-todo-app
  namespace: argocd
spec:
  project: eks-todo-project
  sources:
    - repoURL: https://github.com/Wicky2001/eks-todo-jenkins-gitops.git
      targetRevision: main
      path: migration 
    - repoURL: https://github.com/Wicky2001/eks-todo-jenkins-gitops.git
      targetRevision: main
      path: frontend
    - repoURL: https://github.com/Wicky2001/eks-todo-jenkins-gitops.git
      targetRevision: main
      path: backend
    - repoURL: https://github.com/Wicky2001/eks-todo-jenkins-gitops.git
      targetRevision: main
      path: ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
