apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-todo-app
  namespace: argocd
spec:
  project: eks-todo-project
  sources:
    - repoURL: https://github.com/Wicky2001/eks-todo.git
      targetRevision: main
      path: k8s/app
    - repoURL: https://github.com/Wicky2001/eks-todo.git
      targetRevision: main
      path: k8s/app/frontend # Path 1
    - repoURL: https://github.com/Wicky2001/eks-todo.git
      targetRevision: main
      path: k8s/app/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
