apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-todo-app
  namespace: argocd
spec:
  project: eks-todo-project
  source:
    repoURL: https://github.com/Wicky2001/eks-todo.git
    targetRevision: main
    path: k8s/app
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
