apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend # label by which pod can be selected
    spec:
      containers:
        - name: frontend-container
          ports:
            - containerPort: 8080
          image: 078238935484.dkr.ecr.ap-south-1.amazonaws.com/eks-todo-frontend:192aa8f46777eab080cfb4d6c26bb1997ec755aa
          imagePullPolicy: Always
