name: Deploy Migration Scripts to EKS

on:
  push:
    branches:
      - main
    paths:
      - mongoose/**
      - .github/workflows/migration-deploy.yml

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
  ECR_REPOSITORY: ${{ vars.MIGRATION_ECR_REPOSITORY }}
  K8_NAMESPACE: default

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Update Kubernetes deployment manifest with new image
        run: |
          IMAGE_URI=${{ steps.build-image.outputs.image }}
          yq e '.spec.template.spec.containers[0].image = "'"$IMAGE_URI"'"' -i k8s/app/migration/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add k8s/app/migration/deployment.yaml
          
          git commit -m "ci: update migration image tag to ${{ github.sha }}"
          
          git push

         